Algoritmo "Exemplo02-Creuza02"
// Curso       : [Algoritmo]
// Professor   : Gustavo Guanabara
// Exemplo 02  : Converter Real para dolar
// Autor(a)    : Raíza Cirne Braz
// Data atual  : 05/10/2022
Var
   // Seção de Declarações das variáveis
   reais, dolares: Real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Quantos Reais eu tenho? R$")
   Leia (reais)
   dolares <- reais/5.20
   Escreva ("Posso ter US$", dolares)
fimalgoritmo



