Algoritmo "Exemplo01-OlaMundo"
// Curso   : [Algoritmo]
// Professor   : Gustavo Guanabara
// Descrição   : Escrever na tela: Olá, Mundo!
// Autor(a)    : Raíza Cirne Braz
// Data atual  : 23/09/2022
Var
   // Seção de Declarações das variáveis
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Olá, Mundo!")
   Escreva ("Me livrei da maldição!")
Fimalgoritmo