Algoritmo "ConteAte0"
// Prática 2: Contar de 10 até 0
Var
   contador: Inteiro
Inicio
   contador <- 10 // começo contador com 10
   Enquanto (contador >= 0) faca // Enquanto for >= 0 que é o valor final que eu quero
      EscrevaL(contador)// vai mostrar valor na tela
      contador <- contador - 1 // vai eliminar 1. Cada vez tira uma unidade da variável contadora até chegar a 0.
   FimEnquanto
   EscrevaL ("Terminei de contar")
Fimalgoritmo