Algoritmo "Exemplo03-Creuza03"
// Curso       : [Algoritmo]
// Professor   : Gustavo Guanabara
// Exemplo 03  : Conversão de celsius para fahrenheit
// Autor(a)    : Raíza Cirne Braz
// Data atual  : 05/10/2022
Var
   // Seção de Declarações das variáveis
   F, C: Real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Qual é a temperatura aqui? ")
   Leia (F)
   C <- (F - 32) / 1.8
   Escreva ("No Brasil estaria ", C:4:1)
fimalgoritmo
