Algoritmo "valores-media"
Var
   N1, N2: Inteiro
   M: Real //Números reais são aqueles que tem a parte decimal, isso é, tem a vírgula ou ponto flutuante.
Inicio
      Escreva ("Informe um número: ")
      Leia (N1)
      Escreva ("Informe outro número: ")
      Leia (N2)
      M <- (N1 + N2) / 2 // Média entre dois números
      Escreva ("A média entre", N1, " e", N2, " é igual a", M)
Fimalgoritmo